name: npm run ve:VC

on:
  schedule:
    - cron: "0 4 * * *" # 4:00 AM UTC
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: npm run ve:VC
      - name: Commit changes
        run: |
          git config --global user.email "oxSaturn@proton.me"
          git config --global user.name "oxSaturn"
          git add .
          git commit -m "Run ve:VC"
          git push
